name: Deploy Go Azure Function to function app


env:
  AZURE_FUNCTIONAPP_NAME: "tak-testfunc3"
  GO_VERSION: "1.19"
  GO_ARCH: "amd64"
  GOOS: "linux" 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build handler.go 
      - name: Deploy
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
